### ISSUE TITLE
Trying to use nodemailer in Angularjs and but failed with "undefined is not a function"

### ISSUE THREAD

**Issue by zhiyzuo** [andris9/Nodemailer#384]
Hi,

I am new to nodejs and just trying to use Nodemailer in AnguarJS.

My code in controllers.js looks like this:
```javascript
      var nodemailer = require('nodemailer');
      var smtpTransport = require('nodemailer-smtp-transport');

      var transporter = nodemailer.createTransport(smtpTransport({
            host: 'smtp.gmail.com',
            service: 'gmail',
            port: '465',
            secure: true,
            auth: {
                user: 'username',
                pass: 'password'
            }
        }));

      transporter.sendMail({
            from: 'user@gmail.com', // sender address
            to: 'user@gmail.com', // list of receivers
            subject: 'Hello ✔', // Subject line
            text: 'Hello world ✔', // plaintext body
            html: '<b>Hello world ✔</b>' // html body
      });
```

When I try to send an email, it will give me such error message:
> TypeError: undefined is not a function
    at SMTPConnection.connect (file:///Users/zhiyzuo/Documents/web/zhiyzuo.github.io/static/js/bundle.js:779:28)
    at SMTPTransport.send (file:///Users/zhiyzuo/Documents/web/zhiyzuo.github.io/static/js/bundle.js:1750:16)
    at Nodemailer.<anonymous> (file:///Users/zhiyzuo/Documents/web/zhiyzuo.github.io/static/js/bundle.js:12290:30)
    at Nodemailer._processPlugins (file:///Users/zhiyzuo/Documents/web/zhiyzuo.github.io/static/js/bundle.js:12410:16)
    at Nodemailer.<anonymous> (file:///Users/zhiyzuo/Documents/web/zhiyzuo.github.io/static/js/bundle.js:12286:14)
    at Nodemailer._processPlugins (file:///Users/zhiyzuo/Documents/web/zhiyzuo.github.io/static/js/bundle.js:12410:16)
    at Nodemailer.sendMail (file:///Users/zhiyzuo/Documents/web/zhiyzuo.github.io/static/js/bundle.js:12275:10)
    at l.controllers.controller.$scope.send (file:///Users/zhiyzuo/Documents/web/zhiyzuo.github.io/static/js/bundle.js:167:19)
    at hb.functionCall (file:///Users/zhiyzuo/Documents/web/zhiyzuo.github.io/static/bower_components/angular/angular.min.js:198:424)
    at Cc.(anonymous function).compile.d.on.f (file:///Users/zhiyzuo/Documents/web/zhiyzuo.github.io/static/bower_components/angular/angular.min.js:227:394)

And the corresponding line in bundle.js is:

```javascript

this._socket = tls.connect(this.options.port, this.options.host, opts, this._onConnect.bind(this));
```
I test the webpage after I run this command:
```
$ browserify controllers.js > bundle.js
```

What's wrong?!! Please help me !! Thank you!!

**Comment by andris9** [comment]
You can't open sockets from a web bage, you need to run Nodemailer in your server and not in a browser.

**Comment by zhiyzuo** [comment]
Thank you for the reply!

Does this mean that I cannot use nodeamailer on Github user page?

**Comment by andris9** [comment]
No, you can't. It is not possible to run anything in the browser that requires access to tcp sockets

**Comment by zhiyzuo** [comment]
I see. Thank you so much!

On Monday, February 2, 2015, Andris Reinman <notifications@github.com>
wrote:

> No, you can't. It is not possible to run anything in the browser that
> requires access to tcp sockets
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andris9/Nodemailer/issues/384#issuecomment-72525882>.
>


-- 
Best,
Zhiya
