### ISSUE TITLE
Heroku issue for nodemailer v1.3.0

### ISSUE THREAD

**Issue by justinjwlee** [andris9/Nodemailer#396]
Hi there,

I'm using nodemailer v1.3.0 and it is crashing my heroku server. On localhost its perfectly fine. I'm not running iojs. Any help will be great!

```
2015-03-02T16:43:03.931127+00:00 app[web.1]: POST /v1/user 200 176.824 ms - 175
2015-03-02T16:43:02.578713+00:00 heroku[web.1]: State changed from starting to up
2015-03-02T16:43:04.484436+00:00 app[web.1]: info: Verification SMS sent successfully
2015-03-02T16:43:06.093755+00:00 app[web.1]: Error: write after end
2015-03-02T16:43:06.093764+00:00 app[web.1]:     at ServerResponse.res.json (/app/node_modules/express/lib/response.js:196:15)
2015-03-02T16:43:06.093770+00:00 app[web.1]:     at /app/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:283:20
2015-03-02T16:43:06.093748+00:00 app[web.1]: events.js:85
2015-03-02T16:43:06.093759+00:00 app[web.1]:     at ServerResponse.res.write (/app/node_modules/compression/index.js:94:17)
2015-03-02T16:43:06.093760+00:00 app[web.1]:     at ServerResponse.res.end (/app/node_modules/compression/index.js:111:14)
2015-03-02T16:43:06.135857+00:00 app[web.1]: npm ERR! Exit status 1
2015-03-02T16:43:06.093753+00:00 app[web.1]:             ^
2015-03-02T16:43:06.093762+00:00 app[web.1]:     at ServerResponse.res.send (/app/node_modules/express/lib/response.js:152:8)
2015-03-02T16:43:06.093768+00:00 app[web.1]:     at /app/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/src/smtp-transport.js:85:20
2015-03-02T16:43:06.133723+00:00 app[web.1]: npm ERR! node v0.12.0
2015-03-02T16:43:06.132774+00:00 app[web.1]: npm ERR! Linux 3.13.0-40-generic
2015-03-02T16:43:06.093752+00:00 app[web.1]:       throw er; // Unhandled 'error' event
2015-03-02T16:43:06.093757+00:00 app[web.1]:     at ServerResponse.OutgoingMessage.write (_http_outgoing.js:413:15)
2015-03-02T16:43:06.093772+00:00 app[web.1]:     at SMTPConnection._actionStream (/app/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:929:9)
2015-03-02T16:43:06.088815+00:00 app[web.1]: info: Verification Email sent successfully
2015-03-02T16:43:06.134840+00:00 app[web.1]: npm ERR! npm  v2.5.1
2015-03-02T16:43:06.141750+00:00 app[web.1]:
2015-03-02T16:43:06.093765+00:00 app[web.1]:     at /app/app/controllers/user/user.js:126:10
2015-03-02T16:43:06.136660+00:00 app[web.1]: npm ERR! This is most likely a problem with the kl-server package,
2015-03-02T16:43:06.135657+00:00 app[web.1]: npm ERR! kl-server@0.0.1 start: `node app.js`
2015-03-02T16:43:06.136280+00:00 app[web.1]: npm ERR!
2015-03-02T16:43:06.125487+00:00 app[web.1]:
2015-03-02T16:43:06.137439+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2015-03-02T16:43:06.133402+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2015-03-02T16:43:06.137718+00:00 app[web.1]: npm ERR!     node app.js
2015-03-02T16:43:06.138031+00:00 app[web.1]: npm ERR!     npm owner ls kl-server
2015-03-02T16:43:06.142068+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2015-03-02T16:43:06.093767+00:00 app[web.1]:     at /app/app/controllers/communication/sendmail.js:97:5
2015-03-02T16:43:06.136441+00:00 app[web.1]: npm ERR! Failed at the kl-server@0.0.1 start script 'node app.js'.
2015-03-02T16:43:06.135215+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2015-03-02T16:43:06.137149+00:00 app[web.1]: npm ERR! not with npm itself.
2015-03-02T16:43:06.137885+00:00 app[web.1]: npm ERR! You can get their info via:
2015-03-02T16:43:06.138289+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2015-03-02T16:43:06.142342+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2015-03-02T16:43:06.989463+00:00 heroku[web.1]: State changed from up to crashed
```

**Comment by andris9** [comment]
There doesn't seem to be nothing wrong with Nodemailer here. Nodemailer delivers a message and returns the callback and now you are trying to send some JSON to the user but the HTTP connection is already closed. Sending an email might take time, so you should check if the `res` object is still writable before you try to send any data to user.

**Comment by justinjwlee** [comment]
Its odd because on my localhost (running OSX) it works perfectly fine. I've tried a bunch of things including not closing the smtp transport but its still not working. Its throwing a bunch of errors like this

```
2015-03-03T12:19:04.243942+00:00 app[web.1]:     at /app/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/src/smtp-transport.js:85:20
2015-03-03T12:19:04.243944+00:00 app[web.1]:     at /app/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:283:20
2015-03-03T12:19:04.243946+00:00 app[web.1]:     at SMTPConnection._actionStream (/app/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:929:9)
```

any idea what that might mean? Thanks alot for your help! :)

**Comment by andris9** [comment]
Thats not an error. the line numbers show that Nodemailer returned the callback function with e-mail status info. The error happens after the callback with line

    at ServerResponse.res.json (/app/node_modules/express/lib/response.js:196:15)

Which means that your app received response from Nodemailer and now tries to send some data (probably about the email) as JSON to the user. This fails, since the connection to the user is not active anymore.

**Comment by raulbarriga** [comment]
> Thats not an error. The line numbers show that Nodemailer successfully returns the callback function with e-mail status info. The error happens after the callback with line
> 
> ```
> at ServerResponse.res.json (/app/node_modules/express/lib/response.js:196:15)
> ```
> 
> Which means that your app received response from Nodemailer and now tries to send some data (probably about the email) as JSON to the user. This fails, since the connection to the user is not active anymore.

Where would you see this log? My issue using heroku gives a 404 post request also using axios. The network tab on chrome dev tools shows that it received the payload sent. For a contact form.
