### ISSUE TITLE
Large Attachments Rejected

### ISSUE THREAD

**Issue by jamesmlees** [andris9/Nodemailer#400]
Hopefully I'm not doing something terribly wrong but I'm repeatedly getting messages rejected by gmail's servers when trying to send messages via nodemailer.

The error message states the attachment is too large but I can send the exact same file using SMTP via another application without issue. Strangely a file of `11500469` bytes sends perfectly well, but a file of `11500470` bytes, received the error message:

```
{
    "message": "Error Transmitting File",
    "detail": {
        "code": "EMESSAGE",
        "response": "552-5.2.3 Your message exceeded Google's message size limits. Please visit\n552-5.2.3 http://support.google.com/mail/bin/answer.py?answer=8770 to review our\n552 5.2.3 size guidelines. nb4sm10940064wjc.20 - gsmtp",
        "responseCode": 552
    }
}

```

The link in the error message points to a webpage instructing that the maximum file size is 25MB!

I've attached my code below, just in case I'm doing something super stupid.

```
fs.readFile(files.file.path, function(err, file_buffer){
	res.render('templates/template_file', 
	{
		clientName: user.displayName,
		clientEmail: user.username,
		appName: config.app.title
	},
		function(err, emailHTML) {
				var smtpTransport = nodemailer.createTransport(config.mailer.options);
				var mailOptions = {
					to: config.mailer.to,
					from: config.mailer.from,
					subject: 'Message Subject',
					html: emailHTML,
					attachments: [
						{
							filename: files.file.name,
							content: file_buffer 
						}
					]
				};
			smtpTransport.sendMail(mailOptions, function(err) {
				if(err){
					response_handler('Error', err, 500);
				}
				else{
					response_handler('Success', null, 200);
				}
			});
		});
});
```

**Comment by andris9** [comment]
Actually no idea what is going on there. The limit isn't 25MB per attachment but for the entire message. Or more precisely – Gmail accepts 35MB messages but if you base64 encode a 25MB attachment, you end up with 35MB of encoded data. If you have a single attachment of 11MB then it should fit into the size limit nicely.

**Comment by andris9** [comment]
I have not been able to replicate and no one else has been complaining about this, so I'm closing this issue for now

**Comment by lfrallon** [comment]
Hi, the nodemailer works fine since I deployed the app. But sadly we haven't receive an email as of today. Tried to run the app manually and then got an error response from google mail:

```
Error: Message failed: 552-5.2.3 Your message exceeded Google's message size limits. Please visit
552-5.2.3  https://support.google.com/mail/?p=MaxSizeError to view our size
552 5.2.3 guidelines. s5-20020a170902a50500b00185507b5ef8sm3735828plq.50 - gsmtp
    at SMTPConnection._formatError (myApp/node_modules/nodemailer/lib/smtp-connection/index.js:790:19)
    at SMTPConnection._actionSMTPStream (myApp/node_modules/nodemailer/lib/smtp-connection/index.js:1680:34)
    at SMTPConnection.<anonymous> (myApp/node_modules/nodemailer/lib/smtp-connection/index.js:1158:22)
    at SMTPConnection._processResponse (myApp/node_modules/nodemailer/lib/smtp-connection/index.js:953:20)
    at SMTPConnection._onData (myApp/node_modules/nodemailer/lib/smtp-connection/index.js:755:14)
    at SMTPConnection._onSocketData (myApp/node_modules/nodemailer/lib/smtp-connection/index.js:193:44)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10) {
  code: 'EMESSAGE',
  response: "552-5.2.3 Your message exceeded Google's message size limits. Please visit\n" +
    '552-5.2.3  https://support.google.com/mail/?p=MaxSizeError to view our size\n' +
    '552 5.2.3 guidelines. s5-20020a170902a50500b00185507b5ef8sm3735828plq.50 - gsmtp',
  responseCode: 552,
  command: 'DATA'
}
```

It might be because of the file size attachment limit, but it says it will save it into google drive and just give you the link. The file size attachment is at least 30MB and the email text characters are at least 120+ chars.
