### ISSUE TITLE
Error received

### ISSUE THREAD

**Issue by catalinbararu** [andris9/Nodemailer#477]
Hey guys, i receive an error when i try to use nodemailer, but first let me explain the situation and then show error.
So, i am writting code and testing it on a windows machine (node v0.12.6; npm 2.11.2) and using a samba share to share it on a unix machine (ubuntu; node v0.8.7, npm is not installed). My test code works well on the windows machine, but if i try to run it on ubuntu i get this error : 
{code}
util.js:538
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:538:43)
    at Object.<anonymous> (/opt/xxx/emailTest/node_modules/nodemailer/node_modules/libmime/node_modules/libbase64/lib/libbase64.js:82:6)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/opt/xxx/emailTest/node_modules/nodemailer/node_modules/libmime/src/libmime.js:4:17)
    at Module._compile (module.js:449:26)
{code}

If anyone might know why this is happening and if it can be resolved please reply.

Thank you !

**Comment by catalinbararu** [comment]
I found that i need an older version of nodemailer for the node version i have. Issue can be closed
