### ISSUE TITLE
Nodemailer error - loopback

### ISSUE THREAD

**Issue by Arth95** [andris9/Nodemailer#478]
Hi!
I want to use nodemailer which is builded in loopback framework.
I want to use gmail account. This is my setting:

"transports": [
      {
        "type": "smtp",
        "host": "smtp.gmail.com",
        "auth": {
          "xoauth2": {
            "user": "mymail@gmail.com",
            "clientId": "myID.apps.googleusercontent.com",
            "clientSecret": "mySecret",
            "refreshToken": "myToken"
          }
        }
      }
    ] 

And I got this error:

TypeError: Object #<Object> has no method 'getToken'
    at SMTPConnection._handleXOauth2Token (/home/arth95/Projects/firstCMS/node_modules/loopback/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:961:67)
    at SMTPConnection.login (/home/arth95/Projects/firstCMS/node_modules/loopback/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:233:18)
    at SMTPTransport.<anonymous> (/home/arth95/Projects/firstCMS/node_modules/loopback/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/src/smtp-transport.js:96:24)
    at SMTPConnection.g (events.js:180:16)
    at SMTPConnection.EventEmitter.emit (events.js:92:17)
    at SMTPConnection._actionEHLO (/home/arth95/Projects/firstCMS/node_modules/loopback/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:692:10)
    at SMTPConnection._processResponse (/home/arth95/Projects/firstCMS/node_modules/loopback/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:511:16)
    at SMTPConnection._onData (/home/arth95/Projects/firstCMS/node_modules/loopback/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:357:10)
    at CleartextStream.EventEmitter.emit (events.js:95:17)
    at CleartextStream.<anonymous> (_stream_readable.js:746:14)

Can you help me or have I go to ask someone from loopback?

**Comment by andris9** [comment]
You need to use XOAuth2 module to generate tokens, see [these docs](https://github.com/andris9/nodemailer-smtp-transport#authentication) for example
