### ISSUE TITLE
`.setMessageOption` breakage caused by pulling in latest mailcomposer

### ISSUE THREAD

**Issue by acg** [andris9/Nodemailer#499]
We've been using a pinned version of Nodemailer, v0.3.44, in production. Recently the loose [mailcomposer semver used here](https://github.com/andris9/Nodemailer/blob/v0.3.44/package.json#L28) caused us to pull in the latest mailcomposer, which broke nodemailer with this stacktrace:

    /home/user/node_modules/mongoose/lib/utils.js:413
            throw err;
                  ^
    TypeError: Object #<MailComposer> has no method 'setMessageOption'
        at Nodemailer.setGeneralOptions (/home/user/node_modules/nodemailer/lib/nodemailer.js:241:23)
        at Nodemailer.generateMailObject (/home/user/node_modules/nodemailer/lib/nodemailer.js:196:10)
        at Nodemailer.sendMail (/home/user/node_modules/nodemailer/lib/nodemailer.js:184:10)
        at /home/user/node_modules/nodemailer/lib/nodemailer.js:69:20
        at Nodemailer.validateSettings (/home/user/node_modules/nodemailer/lib/nodemailer.js:173:5)
        at sendMail (/home/user/node_modules/nodemailer/lib/nodemailer.js:63:12)
        at Transport.transport.sendMail (/home/user/node_modules/nodemailer/lib/nodemailer.js:40:9)

If you're up for releasing a Nodemailer v0.3.46 that pins down its dependencies better, we'd definitely use it. If this is too legacy for you to bother with, that's also okay, but in that case consider this a cautionary tale.

**Comment by andris9** [comment]
Would you consider upgrading to 0.7.1 which should be backwards compatible with 0.3.44?

**Comment by acg** [comment]
We would, yes.

**Comment by andris9** [comment]
Try to use v0.7.1 then. Liberal dependency usage is quite unfortunate indeed, sorry about that
