### ISSUE TITLE
Issue popped up just now

### ISSUE THREAD

**Issue by canvas-manik** [andris9/Nodemailer#531]
We have been using this package for quite some time now. the package was working till now (till a couple of hours back). I ran the npm build just now. it started failing now with the following error:

/node_project/node_modules/nodemailer/node_modules/nodemailer-direct-transport/node_modules/smtp-connection/node_modules/isemail/lib/index.js:5
const Dns = require('dns');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/node_project/node_modules/nodemailer/node_modules/nodemailer-direct-transport/node_modules/smtp-connection/src/smtp-connection.js:11:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/node_project/node_modules/nodemailer/node_modules/nodemailer-direct-transport/src/direct-transport.js:4:22)
    at Module._compile (module.js:460:26)

Did anything changed now?

**Comment by andris9** [comment]
Reinstall Nodemailer. There was a short window of time (an hour or so) where a dependency required at least nodejs 4+.
